name: 'lake_analytics'
version: '1.0.0'
config-version: 2

profile: 'lake_analytics'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "INSTALL httpfs; LOAD httpfs;"
  - "INSTALL iceberg; LOAD iceberg;"
  - "CREATE SCHEMA IF NOT EXISTS {{ env_var('ICEBERG_CATALOG_ALIAS', 'iceberg_lake') }}.lake_staging;"
  - "CREATE SCHEMA IF NOT EXISTS {{ env_var('ICEBERG_CATALOG_ALIAS', 'iceberg_lake') }}.lake_curated;"
  - "CREATE SCHEMA IF NOT EXISTS {{ env_var('ICEBERG_CATALOG_ALIAS', 'iceberg_lake') }}.lake_analytics;"

models:
  lake_analytics:
    staging:
      +materialized: view
      +database: memory
      +schema: main
    curated:
      +materialized: table
      +database: "{{ env_var('ICEBERG_CATALOG_ALIAS', 'iceberg_lake') }}"
      +schema: lake_curated
    analytics:
      +materialized: table
      +database: "{{ env_var('ICEBERG_CATALOG_ALIAS', 'iceberg_lake') }}"
      +schema: lake_analytics
